### ISSUE TITLE
Create /projects

### ISSUE THREAD

**Issue by jszwedko** [sfbrigade/codeforsanfrancisco.org#1]
Consider options for creating a projects page (hosted at `/projects`).

Possibilities:

* Jekyll pages
* Jekyll data
* Dynamic pulling from Github (maybe using civic.json?)
* Others?

Eventually we'll want to dynamically populate this based on the work that the UX research group is doing on the project match making to avoid duplication of information (as their app will also require populating similar information to what we will want to display).

**Comment by jasonlally** [comment]
Settled on jekyll pages for this, but we'll want to layer in some additional live data from GitHub where there's a repo or more. Since we have that data in the metadata, it should be easy(ish) to bring in that information through live API calls on project pages.

If we want that same information on the project index, we may want to cache that information as data using a script. 

My inkling is to start with the per project approach and then layer in what we think would be useful metadata to improve discovery or vetting of projects.

**Comment by jszwedko** [comment]
👍 that seems reasonable to me. Since we have a basic `/projects` page setup, I'll close out this issue and we can create new ones for the additional functionality.
